### PR TITLE
Add basic config functionality

### PR DESCRIPTION
**Pull request by Alphare**
This is a start at tackling #3.

I have multiple things that I dislike about the current UI but that are simply matters of taste. I'm sending this so we can at least have a working config while we improve over the design down the line.

### CODE REVIEW

**Comment by ccgauche** [comment]
Would be a good idea to create the config file with the default params if it doesn't exists.

**Comment by ccgauche** [comment]
Also may you use TOML as the config format ? JSON isn't a particularly user friendly format (No comments + serde_json doesn't support formatting json correctly so it is human readable)

**Comment by FerrahWolfeh** [comment]
> serde_json doesn't support formatting json correctly so it is human readable

iirc, serde_json has a pretty_print function to do exactly this.

But I also prefer something like TOML or YAML as a config format.

**Comment by Alphare** [comment]
Sorry, I was planning on using TOML, but my foggy brain forgot (I've been sick for a few days, the only reason I have the time do this actually heh). I'll change this.

@ccgauche I think the suggestion to auto-populate the config file could be interesting, but then I'm worried about the evolution of the config options and the fact that adding new ones (or renaming/moving existing ones) will change what that default file looks like. This is something I'm not too sure how we'd want to handle (especially if you allow comments, because then you'd have to merging in a way that doesn't break the users formatting, etc).

I'll update the MR with using TOML instead

**Comment by ccgauche** [comment]
@Alphare I see what you mean. Migrations could be an option. (Reading the config and populating the rest with defaults then rewriting it if not correct). The thing is I'm afraid the average user won't search for config options in the doc or on github so showing them directly what they can do in the config could be a good idea. (I would also like to have a graphical config panel.

@FerrahWolfeh Yep there is the pretty_print but still the issue of comments remains.

**Pull request merged**
